#!/bin/sh
# converts sound file formats using MIX in RTcmix   -JGG 9/28/00

if [ $# -ne 3 ]
then
   echo  Usage: `basename $0` infile outfile outformat
   echo "       outformat: aiff, aifc, wav, next, sun, ircam, raw"
   exit 1
fi

# validate input ...

if [ ! -e $1 ]
then
   echo Can\'t find input file.
   exit 1
fi

if [ $1 == $2 ]
then
   echo Your input file name is the same as your output file name\!
   exit 1
fi

if [ -e $2 ]
then
   echo Output file name already exists. Delete it first.
   exit 1
fi

if [ $3 != "aiff" -a $3 != "aifc" -a $3 != "wav" -a $3 != "next" \
                  -a $3 != "sun" -a $3 != "ircam" -a $3 != "raw" ]
then
   echo Output format must be one of aiff, aifc, wav, next, sun, ircam, or raw.
   exit 1
fi

srate=`sfprint $1 | awk '/nchans: / {print $2}'`
chans=`sfprint $1 | awk '/nchans: / {print $4}'`
class=`sfprint $1 | awk '/nchans: / {print $6}'`

if [ $chans -ne 1 -a $chans -ne 2 ]
then
   echo Can\'t convert files with more than 2 chans yet. Sorry...
   exit 1
fi

script="\
print_off();
infile = s_arg(0);
outfile = s_arg(1);
format = s_arg(2);
srate = i_arg(3);
chans = i_arg(4);
class = i_arg(5);
set_option(\"audio_off\", \"clobber_on\");
rtsetparams(srate, chans);
rtinput(infile);
if (class == 2)
   rtoutput(outfile, format)
else
   rtoutput(outfile, format, \"float\");
if (chans == 2)
   MIX(0, 0, DUR(), 1, 0, 1)
else
   MIX(0, 0, DUR(), 1, 0);
"
echo $script | CMIX $1 $2 $3 $srate $chans $class

