#!/bin/sh

progname=`basename $0`

if [ $# -lt 1 ]
then
   echo Usage: ${progname} freq [dur [amp]]
   echo "       (freq in Hz or oct.pc; amp 1-32767, 10000 by default)"
   exit
fi

scriptloc=`type -path ${progname}`
scriptloc=`dirname ${scriptloc}`
scriptname=${scriptloc}/tuningfork.sco

if [ $# -eq 1 ] ; then
   CMIX -q $1 < ${scriptname}
elif [ $# -eq 2 ] ; then
   CMIX -q $1 $2 < ${scriptname}
else
   CMIX -q $1 $2 $3 < ${scriptname}
fi

# Note: no way to tell whether this failed, because cmix returns 0
# status after Minc exit(1)  (problem in minc_functions.c)
# If it don't make noise, it don't work  ;-)
