load("WAVETABLE");

print_on(6);

set_option("buffer_count=3");

rtsetparams(44100, 1, 1024);

makegen(1, 7, 1000, 0, 50, 1, 900, 1, 50, 0);
makegen(2, 10, 1000, 1, 0.3, 0.2)

start = 0.0
amp = 100;
freq = 440.0
dur = 4;

WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
WAVETABLE(0, dur, amp, freq);
freq -=2;
