#!/bin/sh
# Play a sound file at a transposition (with optional amp scaling and inskip).
# Only works for mono and stereo files.
# JGG, 7/30/03

if [ $# -lt 2 ]
then
   echo  Usage: `basename $0` file transposition \[inskip, \[ampmult\]\]
   echo "       (transposition in octave.pc)"
   exit 1
fi

flags='-q'

chans=`sfprint $1 | awk '/nchans: / {print $4}'`
if [ $chans -ne 1 -a $chans -ne 2 ]
then
	echo "Input file channel count must be either 1 or 2."
	exit 1
fi
srate=`sfprint $1 | awk '/nchans: / {print $2}'`

script='
srate = f_arg(0);
infile = s_arg(1);
trans = f_arg(2);
inskip = 0;
amp = 1;
if (n_arg() > 3) {
   inskip = f_arg(3);
   if (n_arg() > 4)
      amp = f_arg(4);
}
rtsetparams(srate, 2);
load("TRANS");
rtinput(infile);
chans = CHANS();
dur = DUR() - inskip;
if (trans < 0)
   dur = translen(dur, trans);
if (chans == 1)
   TRANS(0, inskip, dur, amp, trans)
else {
   TRANS(0, inskip, dur, amp, trans, 0, 1)
   TRANS(0, inskip, dur, amp, trans, 1, 0)
}
'
echo $script | CMIX $flags $srate $*

