#!/bin/sh

progname=`basename $0`

if [ $# -lt 1 ]
then
   echo "Usage: ${progname} freq [dur [amp]]"
   echo "       (freq in Hz or oct.pc; amp 1-32767, 10000 by default)"
   exit
fi

flags='-v 1'

script='
sr = 44100;
envramp = 0.1;
default_dur = 0.5;
default_amp = 10000;

freq = f_arg(0);
if (freq <= 0 || freq > sr / 2) {
   printf("freq out of range\n");
   exit(1);
}

dur = default_dur;
amp = default_amp;
if (n_arg() > 1) {
   dur = f_arg(1);
   if (n_arg() > 2) {
      amp = f_arg(2);
   }
}
if (dur < envramp + envramp) {
   printf("dur must be at least %f\n", envramp + envramp);
   exit(1);
}
if (amp < 1 || amp > 32767) {
   printf("amp must be between 1 and 32767\n");
   exit(1);
}

rtsetparams(sr, 2);
load("WAVETABLE");
control_rate(sr);
env = maketable("line", 20000, 0,0, envramp,1, dur-envramp,1, dur,0);
p2 = 0.2;
p3 = 0.05;
if (freq >= sr/4) {
	p2 = p3 = 0;
}
else if (freq >= sr/6) {
	p3 = 0;
}
wavet = maketable("wave", 5000, 1, p2, p3);
WAVETABLE(0.1, dur, mul(amp, env), freq, 0.5, wavet);
'
echo $script | CMIX $flags $*

# Note: no way to tell whether this failed, because cmix returns 0
# status after Minc exit(1)  (problem in minc_functions.c)
# If it don't make noise, it don't work  ;-)
