# Called by Makefile to masssage the html generated by pod2html.
# This will only work line-at-a-time.
#
# Here are the things we're fixing, in order...
#   - change the appearance of horizontal rules
#   - change the quotation mark style
#   - remove some bold face in pfield lists
#     (NB: works only if pfield description spans just one line)
#
# John Gibson, 11/29/03

sed \
-e 's/<HR>/<HR NOSHADE SIZE="2">/g' \
-e 's/``/"/g' \
-e 's/''/"/g' \
-e 's/<DT><STRONG>\(.*\)<\/STRONG>/<DT>\1/' \
$1

