=head1 NAME

gen7 - make a function with any number of straight line segments

=head1 SYNOPSIS

B<makegen>(I<table_number>, 7, I<table_size>,
I<value1>, I<num_elements1>
[, I<valueN-1>, I<num_elementsN-1>, ... ]
I<valueN>)

=head1 DESCRIPTION

Call L<makegen|makegen> from a script with a I<function_type> of 7 to
make a function table with any number of straight line segments.

The I<num_elements> arguments control how many table elements a line
segment spans, as it connects two successive I<value> arguments.

If you want to use this to make table number 1 -- for an amplitude
envelope, for example -- you may find L<setline|setline> more convenient.

L<Gen 5|gen5> works just like gen 7, except that it uses exponential
line segments.

=head1 ARGUMENTS

=over 8

=item I<table_number>

The numeric ID for the function table.

Normally the table will be rescaled to fit between -1 and 1.
Put a negative sign before the number to prevent this.

=item I<table_size>

The size of the function table: how many values it stores.

=item I<value>

The value at the start or end point of a line segment.

=item I<num_elements>

The number of table elements connecting the previous I<value> to the
next I<value>.

The sum of all the I<num_elements> arguments must equal I<table_size>.

=back

=head1 EXAMPLES

   makegen(1, 7, 1000, 0, 200, 1, 600, 0.5, 200, 0)

makes a straight-line ramp from 0 to 1 over 200 table elements,
followed by another ramp from 1 to 0.5 over 600 table elements,
and then a ramp from 0.5 to 0 over 200 table elements.

=begin man

             --------\
           -/         -------\
          /                   -------\
         /                            --------\
       -/                                      -------\
      /                                                -----\
    -/                                                       --\
   /                                                            --\
 -/                                                                --\
/                                                                    --\
------------------------------------------------------------------------

=end man

=begin html
   <p align="center"><img src="images/gen7.png"><p><br>

=end html

=head1 SEE ALSO

L<makegen|makegen>, L<setexp|setexp>, L<gen5|gen5>

