=head1 NAME

multgens - multiply two function tables to create a new one

=head1 SYNOPSIS

B<multgens>(I<new_table>, I<table_A>, I<table_B> [, I<normalize> ])

=head1 DESCRIPTION

Call B<multgens> from a script to make a new function table by multiplying
corresponding points from two existing tables.  These two tables do
not have to be the same size.  The new table will be as large as the
larger of the two existing tables.

=head1 ARGUMENTS

=over 8

=item I<new_table>

The numeric ID for the new function table.

=item I<table_A>

=item I<table_B>

The numeric IDs for the existing function tables.

=item I<normalize>

If this argument is given and is non-zero, then the new function
table will be normalized.  If the table has no negative values, then
its values will be scaled so that they fit between 0 and 1.  If the
table has negative values, its values will be scaled so that they
fit between -1 and 1.

=back

=head1 EXAMPLES

   /* Make six cycles of a sine wave. */
   makegen(1, 10, 1000, 0, 0, 0, 0, 0, 1)

   /* Make an envelope that fades in and out. */
   makegen(2, 6, 200, 0, 0, 1, 1, 2, 0)

   multgens(3, 1, 2)

Table number 3 will contain six cycles of a sine wave, with amplitude
following the fade in/out envelope shape.  The table will have 1000
elements. 

=begin html
   <p align="center"><img src="images/multgens.png"><br>

=end html

=head1 SEE ALSO

L<makegen|makegen>, L<addgens|addgens>, L<copygen|copygen>,
L<offsetgen|offsetgen>, L<scalegen|scalegen>, L<invertgen|invertgen>,
L<reversegen|reversegen>, L<shiftgen|shiftgen>, L<quantizegen|quantizegen>

=head1 AUTHOR

John Gibson E<lt>johgibso at indiana eduE<gt>

