=head1 NAME

spray_init - initialize a random integer spray can

=head1 SYNOPSIS

B<spray_init>(I<spray_table_number>, I<spray_table_size>, I<random_seed>)

=head1 DESCRIPTION

Call B<spray_init> from a script to set up a random integer spray can.
The idea is that you create a table of integers and then use
L<get_spray|get_spray> to retrieve them.  The table contains integers
from zero to one less than the table size.  (Another way to look at
it is that each element takes its index as its value.)  Repeatedly
calling L<get_spray|get_spray> reads the table randomly, but in such
a way that no number appears twice before all the other numbers have
appeared once.

=over 8

=item I<spray_table_number>

The numeric ID for the spray table.  Note that these are distinct
from the tables you create with L<makegen|makegen>.  You can have
as many as 32 tables, numbered from 0 to 31.

=item I<spray_table_size>

The table can have as many as 512 values.

=item I<random_seed>

An integer to seed the random number generator.  Note that this
re-seeds the same random number generator used by L<rand|rand>,
L<random|random>, L<irand|irand>, etc.

=back

=head1 EXAMPLES

See L<get_spray|get_spray> for an example.

=head1 SEE ALSO

L<get_spray|get_spray>,
L<srand|srand>, L<rand|rand>, L<random|random>, L<irand|irand>,
L<pickrand|pickrand>, L<pickwrand|pickwrand>, L<gen20|gen20>

