#!/bin/sh

prof=~/.profile
echo $SCRIPT_NAME: moving existing .profile
mv $prof $prof.before_rtcmix_install
echo $SCRIPT_NAME: creating new .profile
echo 'PATH=/Users/Shared/rtcmix/bin:${PATH}' > $prof
echo 'PS1="\w/:\$ "' >> $prof
echo "alias rm='rm -i'" >> $prof
echo "alias cp='cp -i'" >> $prof
echo "alias mv='mv -i'" >> $prof
echo "alias ls='/bin/ls -F'" >> $prof
