#!/bin/sh

# get location of RTcmix source tree, passed in from Makefile,
# destination dir, and bin architecture ("Intel" or "PPC")
if [ $# -ne 3 ]
then
	echo "Usage: prep-package RTcmix_source_dir dest_dir architecture"
	exit 1
fi
srcdir=$1
destdir=$2
arch=$3

# clean and remake install dir
rm -rf rtcmix
mkdir rtcmix

# copy docs
ditto ../../docs rtcmix/docs
if [ ${destdir} == "/Applications/rtcmix" ]
then
	cp README-Applications.rtf rtcmix/README.rtf
else
	cp README-UsersShared.rtf rtcmix/README.rtf
fi
cp license.txt rtcmix

# copy snd, so that sample_scores work
ditto ../../snd rtcmix/snd

# copy uninstaller script and play symlink to bin
mkdir rtcmix/bin
#cp uninstall-rtcmix-${arch} rtcmix/bin/uninstall-rtcmix
cd rtcmix/bin
ln -s cmixplay play
cd ../..

# copy selected programs to rtcmix/bin
cd ../../bin
ditto DisplayWindow.app ../pkg/osx/rtcmix/bin/DisplayWindow.app
ditto MouseWindow.app ../pkg/osx/rtcmix/bin/MouseWindow.app
cp CMIX ../pkg/osx/rtcmix/bin
cp PCMIX ../pkg/osx/rtcmix/bin
cp PYCMIX ../pkg/osx/rtcmix/bin
cp cmixplay ../pkg/osx/rtcmix/bin
cp cpspch ../pkg/osx/rtcmix/bin
cp pchcps ../pkg/osx/rtcmix/bin
cp rescale ../pkg/osx/rtcmix/bin
cp setup_rtcmixrc ../pkg/osx/rtcmix/bin
cp sfcreate ../pkg/osx/rtcmix/bin
cp sfprint ../pkg/osx/rtcmix/bin
cp sndpeak ../pkg/osx/rtcmix/bin

# copy lib and shlib dirs
cd ..
ditto lib pkg/osx/rtcmix/lib
ditto ${destdir}/shlib pkg/osx/rtcmix/shlib

# delete SCRUB, which we don't want to distribute
rm -f pkg/osx/rtcmix/shlib/libSCRUB.so

# fix shared lib names in executables
cd pkg/osx/rtcmix/bin
install_name_tool -change ${srcdir}/lib/librtcmix.dylib \
	${destdir}/lib/librtcmix.dylib CMIX
install_name_tool -change ${srcdir}/lib/libgen.dylib \
	${destdir}/lib/libgen.dylib CMIX
install_name_tool -change ${srcdir}/lib/librtcmix.dylib \
	${destdir}/lib/librtcmix.dylib PCMIX
install_name_tool -change ${srcdir}/lib/libgen.dylib \
	${destdir}/lib/libgen.dylib PCMIX
install_name_tool -change ${srcdir}/lib/librtcmix.dylib \
	${destdir}/lib/librtcmix.dylib PYCMIX
install_name_tool -change ${srcdir}/lib/libgen.dylib \
	${destdir}/lib/libgen.dylib PYCMIX
cd ../lib
install_name_tool -change ${srcdir}/lib/libgen.dylib \
	${destdir}/lib/libgen.dylib librtcmix.dylib

# fix shared lib paths in shared libs
install_name_tool -id ${destdir}/lib/librtcmix.dylib librtcmix.dylib
install_name_tool -id ${destdir}/lib/libgen.dylib libgen.dylib

cd ../shlib
for i in *.so
do
	install_name_tool -change ${srcdir}/lib/libgen.dylib \
		${destdir}/lib/libgen.dylib $i
done

