#ifndef EMBEDDED
#define RTCMIX_NAME "RTcmix"
#define RTCMIX_MAJOR_VERSION "5"
#define RTCMIX_MINOR_VERSION "7"
#define RTCMIX_MICRO_VERSION "1"
#define RTCMIX_VERSION "5.7.1"

#else // EMBEDDED
#define RTCMIX_NAME "RTcmix-mm"
#define RTCMIX_MAJOR_VERSION "5"
#define RTCMIX_MINOR_VERSION "7"
#define RTCMIX_MICRO_VERSION "1"
#define RTCMIX_VERSION "5.7.1"
#endif // EMBEDDED
