#ifndef EMBEDDED
#define RTCMIX_NAME "RTcmix"
#define RTCMIX_MAJOR_VERSION "5"
#define RTCMIX_MINOR_VERSION "3"
#define RTCMIX_MICRO_VERSION "0"
#define RTCMIX_VERSION "5.3"

#else // EMBEDDED
#define RTCMIX_NAME "RTcmix-mm"
#define RTCMIX_MAJOR_VERSION "5"
#define RTCMIX_MINOR_VERSION "3"
#define RTCMIX_MICRO_VERSION "0"
#define RTCMIX_VERSION "5.3"
#endif // EMBEDDED
